services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: book-author-api:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=default