apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-author-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-author-api
  template:
    metadata:
      labels:
        app: book-author-api
    spec:
      containers:
        - name: book-author-api-container
          image: book-author-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"

---

apiVersion: v1
kind: Service
metadata:
  name: book-author-api-service
spec:
  type: NodePort
  selector:
    app: book-author-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080