apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_PASS: "YXNzZXNzbWVudF9wYXNz"
  MYSQL_ROOT_PASSWORD: "cm9vdF9wYXNz"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_USER: "assessment_user"
  DB_NAME: "assessment_db"
  DB_URL: "jdbc:mysql://proxysql-service:6033/assessment_db"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxysql
  template:
    metadata:
      labels:
        app: proxysql
    spec:
      containers:
        - name: proxysql
          image: proxysql/proxysql:2.6.1
          ports:
            - name: mysql-port
              containerPort: 6033
            - name: admin-port
              containerPort: 6032

---
apiVersion: v1
kind: Service
metadata:
  name: proxysql-service
spec:
  selector:
    app: proxysql
  ports:
    - name: mysql
      protocol: TCP
      port: 6033
      targetPort: 6033
    - name: admin
      protocol: TCP
      port: 6032
      targetPort: 6032

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-primary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-primary
  template:
    metadata:
      labels:
        app: mysql-primary
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-author-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-author-api
  template:
    metadata:
      labels:
        app: book-author-api
    spec:
      containers:
        - name: book-author-api-container
          image: DOCKER_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: book-author-api-service
spec:
  type: NodePort
  selector:
    app: book-author-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080