spring:
  # CHANGE: The application now connects to the query proxy, not directly to a database.
  # The actual URL, username, and password will be injected by Kubernetes via environment variables
  # for better security and flexibility across environments (dev, staging, prod).
  datasource:
    url: ${DB_URL}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Book and Author Management API
    description: A RESTful service for managing books and authors.
    version: 1.0.0

logging:
  level:
    root: WARN
    com.capgemini.twilight.assessment: INFO
    com.capgemini.twilight.assessment.aspect: INFO